version: '3.7'

services:
  portfolio:
    build:
      context: .
      target: develop
    container_name: portfolio
    working_dir: /portfolio
    volumes:
      - .:/portfolio
      - portfolio_modules:/portfolio/node_modules 
      # - /portfolio/node_modules 
    ports:
      - 80:80
    
    entrypoint: /bin/sh -c "quasar dev -p 80"

volumes:
  portfolio_modules:
