version: '3.7'

services:
  portfolio:
    container_name: portfolio
    # build:
    #   context: .
    # image: portfolio:v0.1
    image: ghcr.io/alvarohc777/portfolio:v2.0

    ports:
      - 443:443
      - 80:80

    entrypoint: ["nginx", "-g", "daemon off;"]
